Exception in thread "main" java.io.FileNotFoundException: /home/runner/work/AdventOfCode2022/AdventOfCode2022/main/.github/scripts/../../.github/challenges/10.txt (No such file or directory)
	at java.base@11.0.17/java.io.FileInputStream.open0(FileInputStream.java)
	at java.base@11.0.17/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base@11.0.17/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at clojure.java.io$fn__11617.invokeStatic(io.clj:229)
	at clojure.java.io$fn__11617.invoke(io.clj:229)
	at clojure.java.io$fn__11569$G__11523__11576.invoke(io.clj:69)
	at clojure.java.io$fn__11629.invokeStatic(io.clj:258)
	at clojure.java.io$fn__11629.invoke(io.clj:254)
	at clojure.java.io$fn__11569$G__11523__11576.invoke(io.clj:69)
	at clojure.java.io$fn__11591.invokeStatic(io.clj:165)
	at clojure.java.io$fn__11591.invoke(io.clj:165)
	at clojure.java.io$fn__11530$G__11519__11537.invoke(io.clj:69)
	at clojure.java.io$reader.invokeStatic(io.clj:102)
	at clojure.java.io$reader.doInvoke(io.clj:86)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$slurp.invokeStatic(core.clj:7009)
	at clojure.core$slurp.doInvoke(core.clj:7009)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at challenge$_main.invokeStatic(challenge.clj:9)
	at challenge$_main.doInvoke(challenge.clj:7)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at challenge.main(Unknown Source)
