Traceback (most recent call last):
  File "/home/runner/work/AdventOfCode24/AdventOfCode24/Clashsoft/00/./challenge", line 5, in <module>
    with open(sys.argv[1], "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/AdventOfCode24/AdventOfCode24/main/.github/scripts/../../.github/challenges/00.txt'
