Traceback (most recent call last):
  File "/home/runner/work/AdventOfCode2022/AdventOfCode2022/fhessel/11/./challenge", line 4, in <module>
    with open(sys.argv[1], "r") as txt, open('monkeys.py','w') as py:
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/AdventOfCode2022/AdventOfCode2022/main/.github/scripts/../../.github/challenges/11.txt'
